### ISSUE TITLE
Autoremove from hosts file does not work

### ISSUE THREAD

**Issue by regnerisch** [labor-digital/lab-cli#1]
Entering `lab down` asks me ` Should I also remove the apps entry in your hosts file? (Cleanup to permanently remove the app)` after pressing `Yes` the line inside my hosts file is not removed, which then causes problems when starting.

**Comment by Neunerlei** [comment]
Hey, thanks for posting this issue.

Did the Elevation-Prompt pop up after you pressed enter? 
If so, did you confirm the elevation?

Elevation is required for the script to write the hosts file on your machine.

**Comment by regnerisch** [comment]
No, I do not get any prompt. (Win 10 on Git-Bash)

**Comment by Neunerlei** [comment]
I think the issue is related to spaces in a directory path.
I take a look at it, either this evening or tomorrow 👀

**Comment by Neunerlei** [comment]
This should be fixed with https://github.com/labor-digital/lab-cli/commit/0daa5c3390195cd0a9631d43135c2d5b4f5799e0

I also added graceful handling of existing domains using a nice prompt https://github.com/labor-digital/lab-cli/commit/a3450d06392125c1676a41d0ca72a9f2600a4d72
