### ISSUE TITLE
Version Option missing in LAB 3.4.1

### ISSUE THREAD

**Issue by regnerisch** [labor-digital/lab-cli#2]
I updated to LAB 3.4.1, after running `lab --version` i got 

```sh 
lab --version
Iyi günler, you are using LAB 3.4.1
error: unknown option '--version' 
```

I checked the changelog, no entry found about its removal.

**Comment by Neunerlei** [comment]
I don't think I actively removed it from the script.
As far as the code goes I never implemented it in the public release of this script (which is a complete rewrite in comparison to the legacy "labor cli").  Is it possible that you were using the legacy "labor --version" instead?
Nevertheless, I will re implement this option in the next release 👍

**Comment by regnerisch** [comment]
You are right, I double checked it, I used the old labor-cli. 🤦

**Comment by Neunerlei** [comment]
This should be fixed with https://github.com/labor-digital/lab-cli/commit/f17b7a007ee4bbe88b097688e7f3ad202d8b150d
